### ISSUE TITLE
Plotly graphs

### ISSUE THREAD

**Issue by DamianLodz** [ar-nowaczynski/htmlcreator#7]
Hi, is it possible to put Plotly interactive graphs into a html output using htmlcreator?

**Comment by ar-nowaczynski** [comment]
Plotly allows exporting interactive graphs to HTML as described here: https://plotly.com/python/interactive-html-export/#saving-to-an-html-file

After a quick read I think it should be possible to redirect `plotly.graph_objects.Figure.write_html` output to `io.StringIO` object and then append the string to `HTMLDocument`'s body.

I'll investigate it more in my spare time.

**Comment by DamianLodz** [comment]
I managed to solve this by:

from plotly.io import to_html
fig_html = to_html(your_plotly_fig)

document.body += fig_html1

PS. Da się rozwiązać problem polskich znaków?

**Comment by ar-nowaczynski** [comment]
I'm glad you have found the working solution. I will still try to implement a convenient way to add plotly figures, because I see a way to improve the naive method (for example, if you add multiple figures - it make sense to embed `Plotly.js` source code (3MB) only once to get smaller HTML file).

**Comment by ar-nowaczynski** [comment]
[PL]
Kiedy generuję dokument z polskimi znakami, np. 
```
document.add_text('Ą ą Ć ć Ę ę Ł ł Ń ń Ó ó Ś ś Ź ź Ż ż')
```
to wyświetlają się one w mojej przeglądarce normalnie.

Jedyne co mi przychodzi do głowy to: spróbuj otworzyć wygenerowany html w edytorze tekstu i zmienić: `<html lang="en">` na `<html lang="pl-PL">`. Jeśli to faktycznie pomoże, to dam możliwość ustawienia wartości `lang` z poziomu konstruktora.

**Comment by DamianLodz** [comment]
Niestety nie pomogło, wszystkie polskie znaki dalej w takiej postaci:
![image](https://user-images.githubusercontent.com/50625139/79728241-e5a6df00-82ed-11ea-8a85-cb2034778940.png)

**Comment by ar-nowaczynski** [comment]
Jeśli używasz Windowsa, to trudno mi będzie samemu rozwikłać ten problem, gdyż ja mam dostęp tylko do Linuxa, gdzie powinno działać poprawnie.

Sprawdź, w jaki sposób twój edytor tekstu enkoduje pliki i ewentualnie zmień na utf-8, gdyby było inaczej.

**Comment by ar-nowaczynski** [comment]
Closed by #8 

I have added `add_plotly_figure` method that accepts `plotly.graph_objs.Figure` object and embeds it into the HTML document.

When `add_plotly_figure(fig)` is called for the first time, `plotly.js` library (+3MB) is also embedded into the document's body. This makes output HTML document fully standalone. Subsequent `add_plotly_figure(fig)` calls will know if `plotly.js` was already included and avoid embedding it again. This helps to keep the output file size to a minimum.

To prevent embedding `plotly.js` library into the output HTML document, you need to add all figures via `add_plotly_figure(fig, include_plotlyjs=False)`. The browser will download `plotly.js` library on the fly, when you open document created this way.

Available from version 0.4.0: https://pypi.org/project/htmlcreator/

The example is here:

code: https://github.com/ar-nowaczynski/htmlcreator/blob/master/examples/2_build_document_with_plotly.py

preview: https://htmlpreview.github.io/?https://github.com/ar-nowaczynski/htmlcreator/blob/master/examples/2_document_with_plotly.html
